[project]
name = "multiverse-element-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "baml-py>=0.86.1",
    "crawl4ai>=0.5.0.post8",
    "feedgen>=1.0.0",
    "nio-bot>=1.2.0",
    "pdfminer-six>=20250506",
]
